### ISSUE TITLE
Edit Wiki Entry Error

### ISSUE THREAD

**Issue by nlinguanti** [EllisLab/Wiki#3]
Brand new install of EE5.2.6 / Wiki 3.0.2 - receive this error when attempting to edit a wiki entry:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'm.url' in 'field list':
SELECT `u`.*, `m`.`member_id`, `m`.`screen_name`, `m`.`email`, `m`.`url` FROM (`exp_wiki_uploads` u) JOIN `exp_members` m ON `m`.`member_id` = `u`.`upload_author` WHERE `u`.`wiki_id` = 2 ORDER BY `upload_date` desc LIMIT 10

**Comment by netz0** [comment]
Update to the latest release. It should be fixed once m.url was removed from the queries.

**Comment by CreativePoweredGeek** [comment]
I receive the same error...  EE 5.3.2 fresh install on a local MAMP dev environment. Wiki version 3.0.2
My full stack:
Exception Caught
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'm.url' in 'field list':
SELECT `u`.*, `m`.`member_id`, `m`.`screen_name`, `m`.`email`, `m`.`url` FROM (`exp_wiki_uploads` u) JOIN `exp_members` m ON `m`.`member_id` = `u`.`upload_author` WHERE `u`.`wiki_id` = 1 ORDER BY `upload_date` desc LIMIT 10
ee/legacy/database/drivers/mysqli/mysqli_connection.php:117

Stack Trace: Please include when reporting this error
#0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('SELECT `u`.*, `...')
#1 ee/legacy/database/DB_driver.php(270): CI_DB_mysqli_driver->_execute('SELECT `u`.*, `...')
#2 ee/legacy/database/DB_driver.php(180): CI_DB_driver->simple_query('SELECT `u`.*, `...')
#3 ee/legacy/database/DB_active_rec.php(1138): CI_DB_driver->query('SELECT `u`.*, `...')
#4 user/addons/wiki/mod.wiki.php(4674): CI_DB_active_record->get()
#5 user/addons/wiki/mod.wiki.php(2221): Wiki->files()
#6 user/addons/wiki/mod.wiki.php(411): Wiki->edit('Intro')
#7 ee/legacy/libraries/Template.php(1778): Wiki->__construct()
#8 ee/legacy/libraries/Template.php(1484): EE_Template->process_tags()
#9 ee/legacy/libraries/Template.php(580): EE_Template->tags()
#10 ee/legacy/libraries/Template.php(236): EE_Template->parse('{!-- ra:0000000...', false, 1, false)
#11 ee/legacy/libraries/Template.php(167): EE_Template->fetch_and_parse('', Array, false)
#12 ee/legacy/libraries/Core.php(661): EE_Template->run_template_engine('', '')
#13 ee/legacy/controllers/ee.php(63): EE_Core->generate_page()
#14 [internal function]: EE->index('edit')
#15 ee/EllisLab/ExpressionEngine/Core/Core.php(241): call_user_func_array(Array, Array)
#16 ee/EllisLab/ExpressionEngine/Core/Core.php(110): EllisLab\ExpressionEngine\Core\Core->runController(Array)
#17 ee/EllisLab/ExpressionEngine/Boot/boot.php(151): EllisLab\ExpressionEngine\Core\Core->run(Object(EllisLab\ExpressionEngine\Core\Request))
#18 index.php(173): require_once('...')
#18 index.php(173): require_once('...')
